spring:
  jpa:
    show-sql: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bank_db
    username: root
    password:

  h2:
    console:
      enabled: true
    database:
      console:
        enabled: true
